// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box': string;
  'box2': string;
  'container': string;
  'cord': string;
  'port': string;
  'port-1': string;
  'port-2': string;
  'port-3': string;
  'port-4': string;
  'target1': string;
  'target2': string;
  'x-cord': string;
  'y-cord': string;
}
export const cssExports: CssExports;
export default cssExports;
